###            - - - - - - - - - - - - - - - KNN ALGORITHM - - - - - - - -- - - - - - - -

#### - - - - - - - - - - - - - - - Importing Libraries - - - - - - - - - - - - - - - 

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [3]:
mydata= pd.read_csv("C:\\Users\\josin\\OneDrive\\Desktop\\StudyMaterials\\M2I BIG DATA\machine_learning\\Social_Network_Ads.csv")

In [4]:
mydata.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
mydata.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [9]:
from sklearn.preprocessing import LabelEncoder
mydata['Gender']= LabelEncoder().fit_transform(mydata['Gender'].astype(str))

In [28]:
mydata

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

#### 5. Affectation des variables d’entrée:


In [11]:
X = mydata.iloc[:, [1, 3]].values  # gender & salary
X

array([[     1,  19000],
       [     1,  20000],
       [     0,  43000],
       [     0,  57000],
       [     1,  76000],
       [     1,  58000],
       [     0,  84000],
       [     0, 150000],
       [     1,  33000],
       [     0,  65000],
       [     0,  80000],
       [     0,  52000],
       [     1,  86000],
       [     1,  18000],
       [     1,  82000],
       [     1,  80000],
       [     1,  25000],
       [     1,  26000],
       [     1,  28000],
       [     0,  29000],
       [     1,  22000],
       [     0,  49000],
       [     1,  41000],
       [     0,  22000],
       [     1,  23000],
       [     1,  20000],
       [     1,  28000],
       [     0,  30000],
       [     1,  43000],
       [     1,  18000],
       [     1,  74000],
       [     0, 137000],
       [     0,  16000],
       [     0,  44000],
       [     1,  90000],
       [     1,  27000],
       [     0,  28000],
       [     1,  49000],
       [     0,  72000],
       [     0,  31000],


#### 6. Affectation de la variable de sortie :

In [12]:
Y = mydata.iloc[:, 4].values

#### 7. Séparation de l'ensemble de données en un ensemble d’entrainement et un ensemble de test.

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

#### 8. Nous allons utiliser Feature Scaling pour normaliser la data (Variable de même échelle) et améliorer la performance du modèle.

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#Transformer X_train
X_train = sc.fit_transform(X_train)
#Transformer X_test
X_test = sc.transform(X_test)


In [29]:
X_train

array([[-0.98019606, -0.88670699],
       [ 1.02020406,  1.46173768],
       [-0.98019606, -0.5677824 ],
       [-0.98019606,  1.89663484],
       [-0.98019606, -1.40858358],
       [-0.98019606,  0.99784738],
       [ 1.02020406, -0.79972756],
       [ 1.02020406, -0.24885782],
       [-0.98019606, -0.5677824 ],
       [-0.98019606, -0.19087153],
       [-0.98019606, -1.29261101],
       [ 1.02020406, -0.5677824 ],
       [ 1.02020406,  0.09905991],
       [-0.98019606, -0.59677555],
       [-0.98019606, -1.17663843],
       [ 1.02020406, -0.13288524],
       [-0.98019606,  1.78066227],
       [-0.98019606,  0.56295021],
       [-0.98019606,  0.35999821],
       [-0.98019606, -0.53878926],
       [ 1.02020406, -1.58254245],
       [ 1.02020406,  0.93986109],
       [-0.98019606,  1.22979253],
       [ 1.02020406,  1.08482681],
       [-0.98019606, -0.48080297],
       [ 1.02020406, -0.30684411],
       [ 1.02020406, -0.8287207 ],
       [-0.98019606,  1.8676417 ],
       [-0.98019606,

#### 9. Entraînement du modèle. Nous devons donc importer la bibliothèque scikit.neighbours et y importer le classificateur KNN.

#### 9. Training the model. We therefore need to import the scikit.neighbours library and import the KNN classifier into it.

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier()

#### 10. Prédire les résultats de l'ensemble de test. Nous pouvons prédire les résultats de l'ensemble de test.

#### 10. Predicting the results of the test set. We can predict the results of the test set.

In [25]:

y_pred = classifier.predict(X_test)
#Displaying out the predicted values
print(y_pred)
#Maintenant, pour calculer la précision de notre modèle...
c=0
for i in range(0,len(y_pred)):
    if(y_pred[i]==y_test[i]):
        c=c+1
        accuracy=c/len(y_pred)
print("Accuracy is")
print(accuracy)

[1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1
 1 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 1 0 1]
Accuracy is
0.76


#### 11. Ainsi, lorsque vous exécutez ceci, vous obtenez une précision d'environ 76%, ce qui est un grand succès pour notre classificateur.Maintenant, la section suivante est la visualisation des données, qui nous aide à visualiser la précision et les erreurs de notre modèle.

#### 11. So when you run this, you get an accuracy of about 76%, which is a great success for our classifier.Now, the next section is the data visualization, which helps us visualize the accuracy and errors of our model.

In [ ]:
#Afficher la matrice de confusion
from sklearn.metrics import confusion_matrix


In [30]:
cm = confusion_matrix(y_test, y_pred)
matrice_conf=pd.DataFrame(cm,index=['positive','négative'],columns=['positive','negative'])

In [34]:
cm

array([[55, 13],
       [11, 21]], dtype=int64)

In [33]:
matrice_conf

positive  negative
positive        55        13
négative        11        21

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_test,y_pred)

0.76

#### 12. Refaire l’entrainement en utilisant juste les variables d’entrée suivantes : Gender, salaire et l’Age.

#### 12. Repeat the training using just the following input variables: Gender, salary and Age. 

### ------------------------------------CROSS VALIDATION TECHNIQUE------------------------------

* To find the value of K

In [ ]:
accuracy_rate = []

# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    score=cross_val_score(knn,df_feat,df['EstimatedSalary'],cv=10)
    accuracy_rate.append(score.mean())

In [ ]:
error_rate = []

# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    score=cross_val_score(knn,df_feat,df['EstimatedSalary'],cv=10)
    error_rate.append(1-score.mean())

In [ ]:
error_rate = []

# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))